export type ModelStatus = "production" | "preview" | "blocked";
export type PromotionStage = "candidate" | "benchmark" | "regression" | "shadow" | "canary" | "production";

export type ModelDescriptor = {
  provider: "groq" | "cloudflare" | "gemini" | "mistral" | "nvidia-nim" | "local-webgpu";
  providerModelId: string;
  status: ModelStatus;
  freeEligible: boolean;
  paidRequired: boolean;
  context?: number;
  structuredOutput?: boolean;
  tools?: boolean;
  reasoning?: boolean;
  vision?: boolean;
  audioIn?: boolean;
  embedding?: boolean;
  embeddingDimensions?: number;
  imageOut?: boolean;
  safetyClassifier?: boolean;
  reranker?: boolean;
  localCapability?: "language_detection" | "classification" | "embedding" | "normalization" | "pii_predetection";
  promotionStage?: PromotionStage;
  productionTrafficAllowed?: boolean;
  customerTrafficAllowed?: boolean;
  evalOnly?: boolean;
  license?: string;
  commercialUse?: "allowed" | "review_required";
  attributionRequired?: boolean;
  reviewedAt: string;
};

export const models = {
  "groq:gpt-oss-120b": {
    provider: "groq",
    providerModelId: "openai/gpt-oss-120b",
    status: "production",
    freeEligible: true,
    paidRequired: false,
    context: 131072,
    structuredOutput: true,
    tools: true,
    reasoning: true,
    reviewedAt: "2026-10-06",
  },
  "groq:gpt-oss-20b": {
    provider: "groq",
    providerModelId: "openai/gpt-oss-20b",
    status: "production",
    freeEligible: true,
    paidRequired: false,
    context: 131072,
    structuredOutput: true,
    tools: true,
    reasoning: true,
    reviewedAt: "2026-10-06",
  },
  "groq:qwen3.8-27b": {
    provider: "groq",
    providerModelId: "qwen/qwen3.8-27b",
    status: "preview",
    promotionStage: "candidate",
    freeEligible: true,
    paidRequired: false,
    context: 131042,
    structuredOutput: true,
    tools: true,
    reasoning: true,
    vision: true,
    productionTrafficAllowed: false,
    customerTrafficAllowed: false,
    reviewedAt: "2026-10-07",
  },
  "groq:prompt-guard-2-86m": {
    provider: "groq",
    providerModelId: "meta-llama/llama-prompt-guard-2-86m",
    status: "preview",
    promotionStage: "candidate",
    freeEligible: true,
    paidRequired: false,
    context: 512,
    structuredOutput: true,
    safetyClassifier: true,
    productionTrafficAllowed: true,
    customerTrafficAllowed: false,
    reviewedAt: "2026-10-07",
  },
  "groq:whisper-large-v3-turbo": {
    provider: "groq",
    providerModelId: "whisper-large-v3-turbo",
    status: "production",
    freeEligible: true,
    paidRequired: false,
    audioIn: true,
    reviewedAt: "2026-10-06",
  },
  "cloudflare:glm-4.7-flash": {
    provider: "cloudflare",
    providerModelId: "@cf/zai-org/glm-4.7-flash",
    status: "production",
    freeEligible: true,
    paidRequired: false,
    context: 131072,
    structuredOutput: true,
    tools: true,
    reasoning: true,
    reviewedAt: "2026-10-06",
  },
  "cloudflare:gemma-4-26b-a4b-it": {
    provider: "cloudflare",
    providerModelId: "@cf/google/gemma-4-26b-a4b-it",
    status: "production",
    freeEligible: true,
    paidRequired: false,
    context: 256000,
    tools: true,
    reasoning: true,
    vision: true,
    reviewedAt: "2026-10-06",
  },
  "cloudflare:nemotron-3-120b-a12b": {
    provider: "cloudflare",
    providerModelId: "@cf/nvidia/nemotron-3-120b-a12b",
    status: "production",
    freeEligible: true,
    paidRequired: false,
    context: 32000,
    tools: true,
    reasoning: true,
    reviewedAt: "2026-10-06",
  },
  "cloudflare:whisper-large-v3-turbo": {
    provider: "cloudflare",
    providerModelId: "@cf/openai/whisper-large-v3-turbo",
    status: "production",
    freeEligible: true,
    paidRequired: false,
    audioIn: true,
    commercialUse: "review_required",
    attributionRequired: false,
    reviewedAt: "2026-10-06",
  },
  "cloudflare:embeddinggemma-300m": {
    provider: "cloudflare",
    providerModelId: "@cf/google/embeddinggemma-300m",
    status: "production",
    freeEligible: true,
    paidRequired: false,
    embedding: true,
    embeddingDimensions: 768,
    commercialUse: "review_required",
    attributionRequired: false,
    reviewedAt: "2026-10-06",
  },
  "cloudflare:bge-m3": {
    provider: "cloudflare",
    providerModelId: "@cf/baai/bge-m3",
    status: "preview",
    promotionStage: "candidate",
    freeEligible: true,
    paidRequired: false,
    embedding: true,
    productionTrafficAllowed: false,
    customerTrafficAllowed: false,
    commercialUse: "review_required",
    attributionRequired: false,
    reviewedAt: "2026-10-07",
  },
  "cloudflare:bge-reranker-base": {
    provider: "cloudflare",
    providerModelId: "@cf/baai/bge-reranker-base",
    status: "preview",
    promotionStage: "candidate",
    freeEligible: true,
    paidRequired: false,
    reranker: true,
    productionTrafficAllowed: true,
    customerTrafficAllowed: true,
    commercialUse: "review_required",
    attributionRequired: false,
    reviewedAt: "2026-10-07",
  },
  "cloudflare:flux-1-schnell": {
    provider: "cloudflare",
    providerModelId: "@cf/black-forest-labs/flux-1-schnell",
    status: "production",
    freeEligible: true,
    paidRequired: false,
    imageOut: true,
    commercialUse: "review_required",
    attributionRequired: false,
    reviewedAt: "2026-10-06",
  },
  "gemini:3.5-flash-lite": {
    provider: "gemini",
    providerModelId: "gemini-3.5-flash-lite",
    status: "production",
    freeEligible: true,
    paidRequired: false,
    context: 1048576,
    structuredOutput: true,
    tools: true,
    reasoning: true,
    vision: true,
    commercialUse: "review_required",
    attributionRequired: false,
    reviewedAt: "2026-10-07",
  },
  "gemini:2.5-flash-lite": {
    provider: "gemini",
    providerModelId: "gemini-2.5-flash-lite",
    status: "blocked",
    freeEligible: true,
    paidRequired: false,
    context: 1048576,
    structuredOutput: true,
    tools: true,
    reasoning: true,
    vision: true,
    commercialUse: "review_required",
    attributionRequired: false,
    reviewedAt: "2026-10-07",
  },
  "mistral:small-2603": {
    provider: "mistral",
    providerModelId: "mistral-small-2603",
    status: "preview",
    freeEligible: false,
    paidRequired: true,
    context: 256000,
    structuredOutput: true,
    tools: true,
    reasoning: true,
    license: "Apache-2.0",
    commercialUse: "allowed",
    attributionRequired: false,
    reviewedAt: "2026-10-06",
  },
  "nvidia-nim:gpt-oss-20b-eval": {
    provider: "nvidia-nim",
    providerModelId: "openai/gpt-oss-20b",
    status: "preview",
    promotionStage: "candidate",
    freeEligible: true,
    paidRequired: false,
    context: 131072,
    structuredOutput: true,
    tools: true,
    reasoning: true,
    productionTrafficAllowed: false,
    customerTrafficAllowed: false,
    evalOnly: true,
    commercialUse: "allowed",
    attributionRequired: false,
    reviewedAt: "2026-10-07",
  },
  "local-webgpu:multilingual-classifier": {
    provider: "local-webgpu",
    providerModelId: "Xenova/distilbert-base-multilingual-cased",
    status: "preview",
    promotionStage: "candidate",
    freeEligible: true,
    paidRequired: false,
    localCapability: "classification",
    productionTrafficAllowed: true,
    customerTrafficAllowed: true,
    commercialUse: "review_required",
    attributionRequired: false,
    reviewedAt: "2026-10-07",
  },
  "cloudflare:kimi-k2.7-code": {
    provider: "cloudflare",
    providerModelId: "@cf/moonshotai/kimi-k2.7-code",
    status: "blocked",
    freeEligible: false,
    paidRequired: true,
    reviewedAt: "2026-10-06",
  },
} as const satisfies Record<string, ModelDescriptor>;

export type ModelId = keyof typeof models;
