import type { Sensitivity } from "../../contracts/src/index.js";

export type TaskDefinition = {
  id: string;
  version: number;
  app: string;
  modality: "text" | "vision" | "audio" | "image" | "embedding";
  defaultSensitivity: Sensitivity;
  allowedProviders: string[];
  blockedProviders: string[];
  streaming: boolean;
  capability: string;
  maxOutputTokens: number;
  timeoutMs: number;
  priority: "background" | "interactive" | "critical";
  cache: { mode: "disabled" | "tenant"; ttlSeconds: number };
  rag?: boolean;
};

export const tasks: TaskDefinition[] = [
  { id: "security.prompt_injection.detect", version: 1, app: "nestai", modality: "text", defaultSensitivity: "P2_PERSONAL", allowedProviders: ["groq"], blockedProviders: ["cloudflare","gemini","mistral","nvidia-nim","local-webgpu"], streaming: false, capability: "security:scan", maxOutputTokens: 16, timeoutMs: 5_000, priority: "critical", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "hub.operational.summary", version: 1, app: "millionsnest", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1024, timeoutMs: 15_000, priority: "background", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "hub.incident.explain", version: 1, app: "millionsnest", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: true, capability: "ai:run", maxOutputTokens: 1200, timeoutMs: 15_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 }, rag: true },

  { id: "connect.message.classify", version: 1, app: "connect", modality: "text", defaultSensitivity: "P2_PERSONAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 300, timeoutMs: 8_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "connect.reply.suggest", version: 1, app: "connect", modality: "text", defaultSensitivity: "P2_PERSONAL", allowedProviders: ["groq", "cloudflare"], blockedProviders: ["gemini","mistral"], streaming: true, capability: "ai:run", maxOutputTokens: 768, timeoutMs: 12_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "connect.audio.transcribe", version: 1, app: "connect", modality: "audio", defaultSensitivity: "P2_PERSONAL", allowedProviders: ["cloudflare", "groq"], blockedProviders: ["gemini", "mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 4096, timeoutMs: 60_000, priority: "background", cache: { mode: "disabled", ttlSeconds: 0 } },

  { id: "nestlocal.request.extract", version: 1, app: "nestlocal", modality: "text", defaultSensitivity: "P2_PERSONAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 768, timeoutMs: 12_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "nestlocal.quote.compose", version: 1, app: "nestlocal", modality: "text", defaultSensitivity: "P2_PERSONAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: true, capability: "ai:run", maxOutputTokens: 768, timeoutMs: 12_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "nestlocal.followup.compose", version: 1, app: "nestlocal", modality: "text", defaultSensitivity: "P2_PERSONAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 512, timeoutMs: 10_000, priority: "background", cache: { mode: "disabled", ttlSeconds: 0 } },

  // NestLocal 2.0: explanation / setup / return suggestions only. Never permissions, payment, booking or sends.
  { id: "nestlocal.pulse.explain", version: 1, app: "nestlocal", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 400, timeoutMs: 8_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "nestlocal.setup.assist", version: 1, app: "nestlocal", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 500, timeoutMs: 10_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "nestlocal.return.suggest", version: 1, app: "nestlocal", modality: "text", defaultSensitivity: "P2_PERSONAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 420, timeoutMs: 10_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },

  { id: "journey.form.extract", version: 1, app: "nestjourney", modality: "vision", defaultSensitivity: "P3_SENSITIVE", allowedProviders: ["cloudflare"], blockedProviders: ["groq", "gemini", "mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1536, timeoutMs: 45_000, priority: "background", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "journey.followup.summarize", version: 1, app: "nestjourney", modality: "text", defaultSensitivity: "P2_PERSONAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 700, timeoutMs: 12_000, priority: "background", cache: { mode: "disabled", ttlSeconds: 0 } },

  { id: "finance.receipt.extract", version: 1, app: "nestfinance", modality: "vision", defaultSensitivity: "P3_SENSITIVE", allowedProviders: ["cloudflare"], blockedProviders: ["groq","gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1024, timeoutMs: 20_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "finance.report.explain", version: 1, app: "nestfinance", modality: "text", defaultSensitivity: "P3_SENSITIVE", allowedProviders: ["cloudflare"], blockedProviders: ["groq","gemini","mistral"], streaming: true, capability: "ai:run", maxOutputTokens: 1200, timeoutMs: 20_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "finance.count.regions.extract", version: 1, app: "nestfinance", modality: "vision", defaultSensitivity: "P3_SENSITIVE", allowedProviders: ["cloudflare"], blockedProviders: ["groq","gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1200, timeoutMs: 25_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "finance.count.denominations.extract", version: 1, app: "nestfinance", modality: "vision", defaultSensitivity: "P3_SENSITIVE", allowedProviders: ["cloudflare"], blockedProviders: ["groq","gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 3600, timeoutMs: 30_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "finance.count.freeform.extract", version: 1, app: "nestfinance", modality: "vision", defaultSensitivity: "P3_SENSITIVE", allowedProviders: ["cloudflare"], blockedProviders: ["groq","gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1200, timeoutMs: 25_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "finance.document.transaction.extract", version: 1, app: "nestfinance", modality: "vision", defaultSensitivity: "P3_SENSITIVE", allowedProviders: ["cloudflare"], blockedProviders: ["groq","gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 3600, timeoutMs: 35_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },

  { id: "musicscale.song.structure", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 900, timeoutMs: 12_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "musicscale.team.message.compose", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 700, timeoutMs: 10_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "musicscale.live.diagnostic.explain", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1400, timeoutMs: 12_000, priority: "interactive", cache: { mode: "tenant", ttlSeconds: 900 } },
  { id: "musicscale.live.song-match.assist", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1400, timeoutMs: 12_000, priority: "interactive", cache: { mode: "tenant", ttlSeconds: 900 } },
  { id: "musicscale.live.request.classify", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1400, timeoutMs: 12_000, priority: "interactive", cache: { mode: "tenant", ttlSeconds: 900 } },
  { id: "musicscale.live.search.interpret", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1400, timeoutMs: 12_000, priority: "interactive", cache: { mode: "tenant", ttlSeconds: 900 } },
  { id: "musicscale.live.metadata.normalize", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1400, timeoutMs: 12_000, priority: "interactive", cache: { mode: "tenant", ttlSeconds: 900 } },
  { id: "musicscale.live.post-service.summary", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1400, timeoutMs: 15_000, priority: "background", cache: { mode: "tenant", ttlSeconds: 900 } },
  { id: "musicscale.live.pre-service-risk.explain", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1400, timeoutMs: 15_000, priority: "interactive", cache: { mode: "tenant", ttlSeconds: 900 } },
  { id: "musicscale.chords.repair", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 6000, timeoutMs: 30_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "musicscale.song.import.enrich", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 2200, timeoutMs: 60_000, priority: "interactive", cache: { mode: "tenant", ttlSeconds: 900 } },
  { id: "musicscale.song.suggest", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1400, timeoutMs: 20_000, priority: "interactive", cache: { mode: "tenant", ttlSeconds: 600 } },
  { id: "musicscale.setlist.analyze", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1800, timeoutMs: 20_000, priority: "interactive", cache: { mode: "tenant", ttlSeconds: 600 } },
  { id: "musicscale.release-note.generate", version: 1, app: "musicscale", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1800, timeoutMs: 20_000, priority: "background", cache: { mode: "disabled", ttlSeconds: 0 } },

  { id: "nestlume.study.answer", version: 1, app: "nestlume", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq", "cloudflare"], blockedProviders: ["gemini","mistral"], streaming: true, capability: "ai:run", maxOutputTokens: 1536, timeoutMs: 20_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 }, rag: true },
  { id: "nestlume.study.grounded", version: 1, app: "nestlume", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq", "cloudflare"], blockedProviders: ["gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 2048, timeoutMs: 20_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 }, rag: true },
  { id: "nestlume.entity.explain", version: 1, app: "nestlume", modality: "text", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["groq","cloudflare"], blockedProviders: ["gemini","mistral"], streaming: true, capability: "ai:run", maxOutputTokens: 1200, timeoutMs: 18_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 }, rag: true },
  { id: "nestlume.embedding.generate", version: 1, app: "nestlume", modality: "embedding", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["cloudflare"], blockedProviders: ["groq", "gemini", "mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 0, timeoutMs: 15_000, priority: "background", cache: { mode: "disabled", ttlSeconds: 0 } },

  { id: "affiliate.screenshot.extract", version: 1, app: "nestaffiliate", modality: "vision", defaultSensitivity: "P1_INTERNAL", allowedProviders: ["cloudflare"], blockedProviders: ["groq","gemini","mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 850, timeoutMs: 35_000, priority: "interactive", cache: { mode: "disabled", ttlSeconds: 0 } },
  { id: "affiliate.product.analyze", version: 1, app: "nestaffiliate", modality: "text", defaultSensitivity: "P0_PUBLIC", allowedProviders: ["groq","cloudflare","gemini"], blockedProviders: ["mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 1000, timeoutMs: 15_000, priority: "background", cache: { mode: "tenant", ttlSeconds: 1800 } },
  { id: "affiliate.pin.copy", version: 1, app: "nestaffiliate", modality: "text", defaultSensitivity: "P0_PUBLIC", allowedProviders: ["groq", "cloudflare","gemini"], blockedProviders: ["mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 768, timeoutMs: 12_000, priority: "interactive", cache: { mode: "tenant", ttlSeconds: 1800 } },
  { id: "affiliate.creative.generate", version: 1, app: "nestaffiliate", modality: "image", defaultSensitivity: "P0_PUBLIC", allowedProviders: ["cloudflare"], blockedProviders: ["groq", "gemini", "mistral"], streaming: false, capability: "ai:run", maxOutputTokens: 0, timeoutMs: 60_000, priority: "background", cache: { mode: "disabled", ttlSeconds: 0 } },
];

export function getTask(id: string): TaskDefinition {
  const task = tasks.find((item) => item.id === id);
  if (!task) throw new Error("TASK_NOT_REGISTERED");
  return task;
}
